Host: aritchie.github.io
Title: Personal Blog of Allan Ritchie
SiteTitle: Allan Ritchie
SubTitle: The personal blog of Allan Ritchie
# Description: The personal blog of Allan Ritchie
PostSources: posts/{*,!*source}.md
Image: images/toronto_pan.jpg
LinksUseHttps: true
SamplesUrl: https://samples.shinylib.net/
SamplesUrlDescription: Samples
DocumentationUrl: https://shinyorg.github.io/
DocumentationUrlDescription: Documentation
GitHubUrl: https://github.com/shinyorg/shiny/
AllNugetsUrl: https://www.nuget.org/profiles/ShinyLib
AllNugetsUrlDescription: NuGets