Host: aritchie.github.io
Title: Personal Blog of Allan Ritchie
SiteTitle: Allan Ritchie
SubTitle: The personal blog of Allan Ritchie
# Description: The personal blog of Allan Ritchie
PostSources: posts/{*,!*source}.md
Image: images/toronto_pan.jpg
LinksUseHttps: true
DocumentationUrl: https://shinylib.net/
DocumentationUrlDescription: Documentation
GitHubUrl: https://github.com/shinyorg/
AllNugetsUrl: https://www.nuget.org/profiles/aritchie
AllNugetsUrlDescription: NuGets