name: Deploy Blog
on:
  push:
  schedule:
  - cron: '0 13 * * *'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.202'

    - run: dotnet run -- deploy -l Debug
      env:
        GITHUB_TOKEN: ${{ secrets.BLOG_GITHUB_TOKEN }}